import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Welcome',
    },
    {
      type: 'category',
      label: 'AI Tools',
      link: { type: 'generated-index', description: 'AI infrastructure tool directory — in-depth technical analysis of LLM security, AI observability, orchestration, RAG, agent frameworks, and MLOps tools.' },
      items: [ { type: 'autogenerated', dirName: 'ai-tools' } ],
    },
    {
      type: 'category',
      label: 'Tool Comparisons',
      link: { type: 'generated-index', description: 'Head-to-head technical comparisons of AI infrastructure tools — vector databases, LLM orchestration frameworks, AI gateways, observability platforms, and security tools.' },
      items: [ { type: 'autogenerated', dirName: 'comparisons' } ],
    },
    {
      type: 'category',
      label: 'AIOps',
      link: { type: 'generated-index', description: 'AI for IT Operations — monitoring, anomaly detection, incident management, predictive scaling, and autonomous operations.' },
      items: [ { type: 'autogenerated', dirName: 'aiops' } ],
    },
    {
      type: 'category',
      label: 'AI Architecture',
      link: { type: 'generated-index', description: 'Enterprise AI architecture patterns — secure LLM pipelines, AI observability stacks, DevOps for AI agents, and governance frameworks.' },
      items: [ { type: 'autogenerated', dirName: 'ai-architecture' } ],
    },
    {
      type: 'category',
      label: 'AI Infrastructure',
      link: { type: 'generated-index', description: 'Build and manage AI/ML platforms — GPU clusters, Kubernetes for ML, model serving, and MLOps pipelines.' },
      items: [ { type: 'autogenerated', dirName: 'ai-infra' } ],
    },
    {
      type: 'category',
      label: 'AI Learning',
      link: { type: 'generated-index', description: 'Learn AI from the basics — machine learning, deep learning, NLP, LLMs, prompt engineering, RAG, and AI agents.' },
      items: [ { type: 'autogenerated', dirName: 'ai-learning' } ],
    },
    {
      type: 'category',
      label: 'How-To Guides',
      link: { type: 'doc', id: 'guides/index' },
      items: [ { type: 'autogenerated', dirName: 'guides' } ],
    },
    {
      type: 'category',
      label: 'Decision Guides',
      link: { type: 'doc', id: 'decision-guides/index' },
      items: [ { type: 'autogenerated', dirName: 'decision-guides' } ],
    },
    {
      type: 'category',
      label: 'FinOps & AI Cost Optimization',
      link: { type: 'generated-index', description: 'Guides and case studies on optimizing AI costs, including LLMs, RAG systems, GPU workloads, and observability.' },
      items: [ { type: 'autogenerated', dirName: 'finops-ai' } ],
    },
    {
      type: 'category',
      label: 'Cloud & DevOps',
      link: { type: 'generated-index', description: 'Cloud AI services, CI/CD for ML, model monitoring, and production deployment strategies.' },
      items: [ { type: 'autogenerated', dirName: 'cloud-devops' } ],
    },
    {
      type: 'category',
      label: 'Tool Setup',
      link: { type: 'generated-index', description: 'Setup guides for AI and DevOps tools.' },
      items: [ { type: 'autogenerated', dirName: 'tool-setup' } ],
    },
    {
      type: 'category',
      label: 'Hands-On Labs',
      link: { type: 'generated-index', description: 'End-to-end projects and labs — build real AI applications, AIOps pipelines, and intelligent systems.' },
      items: [ { type: 'autogenerated', dirName: 'labs' } ],
    },
  ],
};

export default sidebars;
